### ISSUE TITLE
Cannot use jest.mock

### ISSUE THREAD

**Issue by martpet** [sodatea/vite-jest#25]
Can you use `jest.mock` ?

With this:
```
import { myFunc } from '~/api';
jest.mock('~/api');
```

I get:
_Cannot find module '~/api' from 'jest.setup.js'_

If I change it:
`jest.mock('./src/api');`

The error is gone, but `myFunc` is not mocked.

Here is my code:
https://github.com/martpet/vite-play/blob/Add-tests/src/store/features/translations/translationsThunks.test.ts

**Comment by breytex** [comment]
What was the issue here? @martpet

**Comment by martpet** [comment]
jest.mock doesn't work with ES modules, but there is now jest.unstable_mockModule which is supposed to work.
